### ISSUE TITLE
IPacket tightly coupled to BigEndianBinaryWriter and BigEndianBinaryReader

### ISSUE THREAD

**Issue by aelsi2** [Scrap-Mechanic-Modding/SM_Server#2]
The parameter types in `IPacket.Serialize` and `IPacket.Deserialize` should be changed from `BigEndianBinaryWriter` and `BigEndianBinaryReader` to `BinaryWriter` and `BinaryReader` respectively for decoupling.

**Comment by arcturus-prime** [comment]
Just fixed it, thanks!
